CREATE TABLE PRICES (
    PRICE_ID BIGINT PRIMARY KEY,
    BRAND_ID VARCHAR(255),
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST VARCHAR(255),
    PRODUCT_ID VARCHAR(255),
    PRIORITY INT,
    PRICE DECIMAL(10, 2),
    CURR VARCHAR(3)
);
